const MAX_USER_TASKS = 50
const TASK_PENDING_PATCH_NAMESPACE = 'task-pending-patch'
const TASK_PATCH_FLUSH_DEBOUNCE_MS = 3000
const TASK_PENDING_OPS_STORAGE_KEY = 'agenda:task-pending-ops'

export {
    MAX_USER_TASKS,
    TASK_PENDING_PATCH_NAMESPACE,
    TASK_PATCH_FLUSH_DEBOUNCE_MS,
    TASK_PENDING_OPS_STORAGE_KEY,
}
